version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: server-manager-app:dev
    container_name: server-manager-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - smnet

  redis:
    image: redis:7-alpine
    container_name: server-manager-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - smnet

  nginx:
    image: nginx:1.25-alpine
    container_name: server-manager-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - smnet

networks:
  smnet:
    driver: bridge 