# FrankenPHP Configuration for Server Manager
# This file configures FrankenPHP for the Laravel application

[server]
# Listen on all interfaces
addr = ":80"

# Enable HTTP/2 and HTTP/3
http2 = true
http3 = true

# Enable compression
compression = true

# Worker processes
workers = 1

# PHP settings
[php]
# PHP-FPM settings
fpm = false  # We're using embedded PHP

# PHP configuration
ini = [
    "memory_limit = 512M",
    "max_execution_time = 300",
    "upload_max_filesize = 100M",
    "post_max_size = 100M",
    "max_input_vars = 3000",
    "display_errors = On",
    "log_errors = On",
    "error_log = /var/www/html/storage/logs/php_errors.log",
    "session.save_handler = redis",
    "session.save_path = tcp://redis:6379",
    "opcache.enable = 1",
    "opcache.enable_cli = 1",
    "opcache.memory_consumption = 128",
    "opcache.interned_strings_buffer = 8",
    "opcache.max_accelerated_files = 4000",
    "opcache.revalidate_freq = 2",
    "opcache.fast_shutdown = 1"
]

# Static file serving
[static]
# Serve static files from public directory
root = "/var/www/html/public"

# Cache static files
cache = true
cache_duration = "1h"

# Security headers
[headers]
# Security headers for all responses
default = [
    "X-Content-Type-Options: nosniff",
    "X-Frame-Options: DENY",
    "X-XSS-Protection: 1; mode=block",
    "Referrer-Policy: strict-origin-when-cross-origin",
    "Permissions-Policy: geolocation=(), microphone=(), camera=()"
]

# CORS headers for API responses
api = [
    "Access-Control-Allow-Origin: *",
    "Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS",
    "Access-Control-Allow-Headers: Content-Type, Authorization"
] 